### ISSUE TITLE
Could not load main class com.amazon.aes.webservices.client.cmd.RunInstances

### ISSUE THREAD

**Issue by Poojagrv** [kowalcj0/gee#8]
Hi,

I was trying this solution but when i execute the script it gives below error 

requesting 1 instance(s)...Error: Could not find or load main class com.amazon.aes.webservices.client.cmd.RunInstances
Caused by: java.lang.ClassNotFoundException: com.amazon.aes.webservices.client.cmd.RunInstances

Could you please suggest something on this?

Regards,
Pooja

**Comment by kowalcj0** [comment]
Hi Poojagrv,

I haven't used this project since the last commit in 2014.
Most likely EC2 API or one of dependencies had changed since then.
I'm sorry but I won't be able to help you with this.

Thanks
